name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
          env:
            CI: false
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
          env:
            CI: false
          
        
